CREATE SEQUENCE FLIGHT_SEQ MINVALUE 1 MAXVALUE 50000 START WITH 1 INCREMENT BY 2;
CREATE SEQUENCE PASSENGER_SEQ MINVALUE 1 MAXVALUE 50000 START WITH 1 INCREMENT BY 2;
CREATE SEQUENCE PLANE_SEQ MINVALUE 1 MAXVALUE 50000 START WITH 1 INCREMENT BY 2;
CREATE SEQUENCE FLIGHT_PASSENGER_SEQ MINVALUE 1 MAXVALUE 50000 START WITH 1 INCREMENT BY 2;