CREATE TABLE FLIGHT (
  ID NUMBER,
  CONSTRAINT FLIGHT_PK PRIMARY KEY (ID),
  PLANE NUMBER,
  CONSTRAINT PLANE_FK FOREIGN KEY (PLANE) REFERENCES PLANE (ID),
  DATE_FLIGHT TIMESTAMP(6) WITH TIME ZONE,
  CITY_FROM NVARCHAR2(100) NOT NULL,
  CITY_TO NVARCHAR2(100) NOT NULL
  );