CREATE TABLE PLANE (
  ID NUMBER,
  CONSTRAINT PLANE_PK PRIMARY KEY (ID),
  MODEL_PLANE NVARCHAR2(200) NOT NULL,
  CODE NVARCHAR2(200) NOT NULL,
  YEAR_PRODUCED TIMESTAMP(6) WITH TIME ZONE,
  AVG_FUEL_CONSUMPTION NUMBER(8,2)
  );