CREATE TABLE FLIGHT_PASSENGER (
  FLIGHT_ID NUMBER NOT NULL,
  PASSENGER_ID NUMBER NOT NULL,
  PRIMARY KEY (FLIGHT_ID, PASSENGER_ID),
  CONSTRAINT FK_FLIGHT_ID FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT (ID),
  CONSTRAINT FK_PASSENGER_ID FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER (ID)
  );