CREATE TABLE PASSENGER (
  ID NUMBER,
  CONSTRAINT PASSENGER_PK PRIMARY KEY (ID),
  LAST_NAME NVARCHAR2(100),
  NATIONALITY NVARCHAR2(200),
  DATE_OF_BIRTH TIMESTAMP(6) WITH TIME ZONE,
  PASSPORT_CODE NVARCHAR2(100) NOT NULL
  );